//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarkAndJulia.Website
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MarkAndJuliaContext : DbContext
    {
        public MarkAndJuliaContext()
            : base("name=MarkAndJuliaContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ContactUs> ContactUs { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<OrderOfTheDay> OrderOfTheDays { get; set; }
        public DbSet<Rsvp> Rsvps { get; set; }
    }
}
