//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarkAndJulia.Website
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderOfTheDay
    {
        public int OrderOfTheDayId { get; set; }
        public System.DateTime Date { get; set; }
        public string Event { get; set; }
        public string Notes { get; set; }
    }
}
